=== faironnerie-abc/cabanes-2k17/modeles/data/PlacementCabane.dtd
<!ELEMENT cabanes (groupe+)>
<!ELEMENT groupe (taille,cabane+)>
<!ATTLIST groupe id CDATA #REQUIRED>
<!ENTITY % coordonnee "(ligne,colonne)" >
<!ELEMENT ligne (#PCDATA)>
<!ELEMENT colonne (#PCDATA)>
<!ELEMENT taille %coordonnee;>
<!ELEMENT cabane (coordonnee,orientation)>
<!ELEMENT coordonnee %coordonnee;>
<!ELEMENT orientation (#PCDATA)>

=== faironnerie-abc/cabanes-2k17/modeles/data/PlacementCabane.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE cv SYSTEM "PlacementCabane.dtd">
<cabanes>
  <groupe id="1">
    <taille>
      <ligne>1</ligne>
      <colonne>23</colonne>
    </taille>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>0.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>2.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>4.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>6.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>8.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>10.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>12.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>14.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>16.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>18.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>20.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>22.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>24.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>26.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>28.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>30.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>32.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>34.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>36.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>38.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>40.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>42.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>44.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
  </groupe>
  <groupe id="2">
    <taille>
      <ligne>1</ligne>
      <colonne>27</colonne>
    </taille>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>60.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>62.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>64.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>66.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>68.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>70.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>72.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>74.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>76.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>78.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>80.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>82.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>84.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>86.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>88.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>90.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>92.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>94.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>96.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>98.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>100.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>102.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>104.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>106.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>108.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>110.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>112.0</colonne>
      </coordonnee>
      <orientation>ouest</orientation>
    </cabane>
  </groupe>
  <groupe id="3">
    <taille>
      <ligne>11</ligne>
      <colonne>6</colonne>
    </taille>
    <cabane>
      <coordonnee>
        <ligne>0.0</ligne>
        <colonne>148.0</colonne>
      </coordonnee>
      <orientation>sud</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>2.0</ligne>
        <colonne>148.0</colonne>
      </coordonnee>
      <orientation>sud</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>4.0</ligne>
        <colonne>148.0</colonne>
      </coordonnee>
      <orientation>sud</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>6.0</ligne>
        <colonne>148.0</colonne>
      </coordonnee>
      <orientation>sud</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>8.0</ligne>
        <colonne>148.0</colonne>
      </coordonnee>
      <orientation>sud</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>10.0</ligne>
        <colonne>148.0</colonne>
      </coordonnee>
      <orientation>sud</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>12.0</ligne>
        <colonne>148.0</colonne>
      </coordonnee>
      <orientation>sud</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>14.0</ligne>
        <colonne>148.0</colonne>
      </coordonnee>
      <orientation>sud</orientation>
    </cabane>
    <cabane>
      <coordonnee>
        <ligne>16.0</ligne>
